name: Release

on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      release-id:
        description: Release ID
        type: string
        required: true
      skip-github-feed:
        description: Do not push to GitHub Feed
        type: boolean
        required: false
        default: false
      skip-nuget-feed:
        description: Do not push to NuGet Feed
        type: boolean
        required: false
        default: false

jobs:
  release-to-nuget:
    uses: libanvl/ci/.github/workflows/release-to-nuget.yml@main
    if: ${{ github.event_name == 'release' }}
    with:
      release-id: ${{ github.event.release.id }}
      push-github-feed: true
      push-nuget-feed: true
    secrets: inherit

  release-to-nuget-manual:
    uses: libanvl/ci/.github/workflows/release-to-nuget.yml@main
    if: ${{ github.event_name == 'workflow_dispatch' }}
    with:
      release-id: ${{ github.event.inputs.release-id }}
      push-github-feed: ${{ github.event.inputs.skip-github-feed != 'false' }}
      push-nuget-feed: ${{ github.event.inputs.skip-nuget-feed != 'false' }}
    secrets: inherit
